id: P5AC9FE75
initial_creation_type: ocr
source_metadata:
  volumes:
    26b7c80c3b7948db86982220253d462e:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: སྔགས་ཀྱི་རྒྱན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1853
      volume_number: 25
