id: P5AC9FE75
initial_creation_type: ocr
source_metadata:
  volumes:
    e1968fd3295e4ac790b69fcf8c1c95cb:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: སྔགས་ཀྱི་རྒྱན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1853
      volume_number: 25
